# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11241d65b24608125aa804b1e06dde271dccf4f510501fb88bf5518cdf32f70a38ce8ad6aee065f74d8922c61c8cb10e3ce254fd39bc7ef73483ee6bcb41f9e2

test:
  secret_key_base: 117ee4dac851d5aa891a4fe36541087a53fe6feec828c93e63a470e11333bacb3e17863d1bff3196d08627792c7653ac38b3003c6ce1d994d924183dd3e97483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: cc0c1beb361a4878636365d9b216c03eb3f95337529577c6f0686c0decc6de44913b2d5c928f1b39815ec505a41d5ada31a37b8732659e33c48575a58599572a
